services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waste-classifier-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_HOST: ${REDIS_HOST}
      MINIO_ENDPOINT: minio:9000
      MODEL_WEIGHTS_PATH: http://minio:9000/models/yolov8s_final.pt
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db
      - redis
      - minio
    volumes:
      - ./app:/app/app

  db:
    image: postgres:15-alpine
    container_name: waste-classifier-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: waste-classifier-redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: waste-classifier-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data: